service:
  name: s3-db

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  environment:
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    BOTTOM_HALF_LAMBDA: ${self:custom.BOTTOM_HALF_LAMBDA}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

custom:
  BOTTOM_HALF_LAMBDA: ${self:service.name}-${self:provider.stage}-defer

functions:
  put:
    handler: src/db.topHalf
    timeout: 6
    events:
      - http:
          method: put
          path: /{actorName}
  get:
    handler: src/db.get
    events:
      - http:
          method: get
          path: /{actorName}
  defer:
    handler: src/db.bottomHalf
    timeout: 900
