service:
  name: s3-db

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  environment:
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  put:
    handler: src/handler.put
    timeout: 900
    events:
      - http:
          method: put
          path: /
  get:
    handler: src/handler.get
    events:
      - http:
          method: get
          path: /
# Lambda timeout
# Lock TTL
# Lock owner
